### ISSUE TITLE
[IMPROVEMENT] Callouts

### ISSUE THREAD

**Issue by motrellin** [FLBadoras/wiki#134]
### Grobbeschreibung

Vorbereitung von verschiedenen Callouts

### Beschreibung

Es gibt bereits zwei in der `_config.yml` definierte Callouts:
```yml
callouts:
  note:
    title: Note
    color: blue
  contributing:
    title: Contributing
    color: yellow
```
Verwendet man die auf der Website, sehen die dann bspw. so aus:
![grafik](https://github.com/FLBadoras/wiki/assets/105235679/c24facd9-5f6a-4f8e-af75-97b32e606e3e)

Es wäre vielleicht sinnvoll, generell mal solche Callouts vorzubereiten, um diese schnell einbauen zu können.

Um das vielleicht mal bei Gelegenheit durch zu "copy/pasten", könnte man die mal hier sammeln.
